### ISSUE TITLE
[Feature] List Series

### ISSUE THREAD

**Issue by TheBeege** [CodeSeoul/event_member_management#1]
This can be based on the Event List function. Create a Series Model, a Series Controller, and a Series Router. Use Event List as a reference.

**Comment by kzkaneoka** [comment]
Hi @TheBeege, thanks for creating a such nice project!

- Can I work on this issue? If it is okay, do you want me to add any additional columns for the Series Model other than the columns mentioned in [the seed data up SQL file](https://github.com/CodeSeoul/event_member_management/blob/master/migrations/up/20201224413917-seedData-up.sql)?
- Also, in [the Event Model](https://github.com/CodeSeoul/event_member_management/blob/master/api/event/model.ts), should I keep the type of series as `any` or should I change it as `number[]`?
- Lastly, how should I add test cases?

**Comment by TheBeege** [comment]
Hey @kzkaneoka ! Yeah, I'm looking forward to working together with people on it. Thanks for helping!
* Yes, I'll assign it to you once I figure out how. Most of my experience is with Jira and Gitlab, so I'll be learning, too. Feel free to add any columns you may think would be needed, and update the migration file as necessary. We'll lock down migrations once I get the system setup; until then,  feel free to edit as necessary. 
* In the Event Model, you'll want to change series to a list of SeriesModel objects once you've defined them. 
* I'm working on tests now. I'm having a bit of trouble with mocking, but I hope to have some examples up today or tomorrow. 
Let me know if you have more questions!

**Comment by kzkaneoka** [comment]
Hi @TheBeege, thanks for assigning! Two more questions :)

- Which branch should I create PR for? master or feature/infra?
- Git shows diff for `package-lock.json` even I just did `npm install`. Should I include/exclude `package-lock.json` in PR?

Thanks!

**Comment by TheBeege** [comment]
Hey @kzkaneoka . 

* Please create the PR for master.
* Huh, strange. It may have been a mistake on my part. Please include it. If there is an issue, I'll fix it. 

Thanks!

**Comment by kzkaneoka** [comment]
Hi @TheBeege,

I created the above PR. Please review it when you have time.

[Npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks) tells why `npm install` overwrites `package-lock.json` and also says:

> It is highly recommended you commit the generated package lock to source control

However, I didn't include `package-lock.json` in this PR because `git diff` showed thousands of line deletions in `package-lock.json`. Instead, I used [npm ci](https://docs.npmjs.com/cli/v6/commands/npm-ci) to install the modules where no diff happened in `package-lock.json`.

Thanks!

**Comment by TheBeege** [comment]
Excellently done! Thank you @kzkaneoka !

I'll need to rework some things due to a major change I made, but I think it will be easier. I'll message you once I get my changes merged.
